name: WalkToDo
main: WalkToDo\WalkToDo;
version: 1.0.0-alpha
api: [3.0.0, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6]
author: Thouv

commands:
  walktodo:
    description: "Adds a new WalkToDo block"
    permission: walktodo.command
    
permissions:
  walktodo:
    description: "Allows access to all WalkToDo features"
    default: op
    children:
      walktodo.command:
        description: "Allows access to /walktodo"
        default: op
      walktodo.walk:
        description: "Allows the player to run commands when walking over WalkToDo blocks"
        default: true
